name: dummy_flightpath
run-name: Dummy run by @${{ github.actor }}
on: [workflow_dispatch]
jobs:
  run_flightpath:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
      - name: Run run_flightpath.py script
        run: |
          python tbx/core/utils/scripts/run_flightpath.py --destination=${{ secrets.HEROKU_APP_NAME_STAGING }}
        env:
          HEROKU_APP_NAME_PRODUCTION: ${{ secrets.HEROKU_APP_NAME_PRODUCTION }}
          FLIGHTPATH_AUTH_KEY: ${{ secrets.FLIGHTPATH_AUTH_KEY }}
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
          FLIGHTPATH_URL: ${{ secrets.FLIGHTPATH_URL }}
